import Chat from "@/app/components/Chat.js";

export const metadata = {
  title: "Chat",
  description: "Generated by create next app",
  icons: {
    icon: "/chat.png",
  },
};

export default function ChatPage() {
    return (
        <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] bg-fixed ">
            <Chat />
        </div>
    );
}