import Profile from "@/app/components/profile";
import { Suspense } from "react";

export const metadata = {
  title: "Your Profile",
  description: "Generated by create next app",
  icons: {
    icon: "/profile.png",
  },
};

export default function profilePage() {

  return (
    <Suspense fallback={
      <div className="w-full pt-32 pb-24 flex justify-center items-start px-4">
        <div className="w-20 h-20 border-4 border-slate-100 border-t-indigo-600 rounded-full animate-spin"></div>
      </div>
    }>
      <Profile />
    </Suspense>
  );
}