import Login from "@/app/components/Login.js";

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
  icons: {
    icon: "/auth.png",
  },
};

export default function LoginPage() {
  return (
    <>  
    <Login />
    </>
  );
}