import Register from "@/app/components/Register.js";

export const metadata = {
  title: "Register",
  description: "Generated by create next app",
  icons: {
    icon: "/auth.png",
  },
};

export default function RegisterPage() {
  return (
    <>  
    <Register />
    </>
  );
}